"""DataAnalyst agent with view-first SQL routing and local execution."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from statistics import mean
from typing import Any

from config.prompts import DATA_ANALYST_SYSTEM_PROMPT
from utils.llm_client import chat_completion
from utils.local_store import QueryResult, run_query
from utils.query_router import QueryRoute, decide_query_route
from utils.schema import BASE_TABLES, render_schema_context


@dataclass(frozen=True)
class AnalysisDraft:
    """A safe SQL draft and routing metadata."""

    sql: str
    route: QueryRoute
    schema_context: str


@dataclass(frozen=True)
class QueryTask:
    """One SQL task planned by the DataAnalyst agent."""

    name: str
    sql: str
    purpose: str


DANGEROUS_SQL_PATTERN = re.compile(
    r"\b(insert|update|delete|drop|alter|create|replace|truncate|attach|detach|pragma|vacuum)\b",
    re.IGNORECASE,
)


def _extract_json_object(content: str) -> dict[str, Any]:
    """Parse a JSON object from the LLM response and fail loudly on invalid output."""
    cleaned = content.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start < 0 or end < start:
        raise ValueError("大模型未返回 JSON 对象，无法生成 SQL 任务")
    try:
        parsed = json.loads(cleaned[start : end + 1])
    except json.JSONDecodeError as exc:
        raise ValueError(f"大模型 SQL 计划 JSON 解析失败：{exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("大模型 SQL 计划不是 JSON 对象")
    return parsed


def _validate_sql(sql: str) -> str:
    """Allow only read-only SELECT/WITH statements generated by the LLM."""
    normalized = sql.strip().rstrip(";")
    lowered = normalized.lower()
    if not (lowered.startswith("select") or lowered.startswith("with")):
        raise ValueError(f"大模型生成了非只读 SQL：{sql}")
    if DANGEROUS_SQL_PATTERN.search(normalized):
        raise ValueError(f"大模型生成了危险 SQL：{sql}")
    if ";" in normalized:
        raise ValueError("大模型一次只能返回一条 SQL")
    if not re.search(r"\blimit\s+\d+\b", lowered):
        normalized = f"{normalized} LIMIT 200"
    return normalized


def plan_tasks_with_llm(question: str) -> tuple[QueryTask, ...]:
    """Use the configured remote LLM as the runtime SQL planner.

    这里不做本地模板兜底：模型不可用、JSON 非法或 SQL 非只读都会向上抛错，
    让前端真实展示问题，而不是用写死 SQL 制造完成假象。
    """
    allowed_base_tables = ", ".join(sorted(BASE_TABLES))
    prompt = f"""
用户问题：
{question}

数据字典：
{render_schema_context()}

规划要求：
1. 你是数据分析 Agent，需要把问题拆成 1 到 6 个 SQL 任务。
2. 优先使用 mv_* 预聚合表；只有视图不能覆盖时才 JOIN 基础表。
3. 所有 SQL 必须是 SQLite 兼容的只读 SELECT 或 WITH 查询。
4. 时间使用 substr(timestamp, 1, 7) 或 date/strftime；百分比字段返回 0-1 小数。
5. 需要预测未来6周时，请至少返回 mv_weekly_sales 的 week_start,total_gmv 序列。
6. 地图/地域问题优先使用 mv_state_geo；差评原因优先使用 mv_review_category_perf；重量运费优先使用 mv_weight_freight。
7. 基础表只允许这些：{allowed_base_tables}。

只返回 JSON，不要 Markdown。格式：
{{
  "tasks": [
    {{"name": "short_snake_case", "purpose": "中文用途", "sql": "SELECT ..."}}
  ]
}}
""".strip()
    response = chat_completion(DATA_ANALYST_SYSTEM_PROMPT, prompt, max_tokens=1800)
    payload = _extract_json_object(response.content)
    raw_tasks = payload.get("tasks")
    if not isinstance(raw_tasks, list) or not raw_tasks:
        raise ValueError("大模型 SQL 计划缺少 tasks")
    tasks: list[QueryTask] = []
    for index, raw_task in enumerate(raw_tasks[:6], start=1):
        if not isinstance(raw_task, dict):
            raise ValueError("大模型 SQL 任务格式错误")
        raw_sql = str(raw_task.get("sql") or "").strip()
        if not raw_sql:
            raise ValueError("大模型 SQL 任务缺少 sql")
        name = str(raw_task.get("name") or f"task_{index}").strip()
        purpose = str(raw_task.get("purpose") or name).strip()
        tasks.append(QueryTask(name=name, sql=_validate_sql(raw_sql), purpose=purpose))
    return tuple(tasks)


@dataclass(frozen=True)
class DataAnalysis:
    """Executed analysis output shared with downstream agents."""

    question: str
    sql: str
    tasks: tuple[QueryTask, ...]
    route: QueryRoute
    routes: dict[str, QueryRoute]
    result: QueryResult
    results: dict[str, QueryResult]
    summary: str
    direct_answer: str


def draft_tasks(question: str) -> tuple[QueryTask, ...]:
    """Ask the real LLM to plan view-first SQL tasks for the user question."""
    return plan_tasks_with_llm(question)


def draft_sql(question: str) -> AnalysisDraft:
    """Draft the primary view-first SQL statement for compatibility with tests."""
    sql = draft_tasks(question)[0].sql
    return AnalysisDraft(sql=sql, route=decide_query_route(sql), schema_context=render_schema_context())


def _percent(value: object) -> str:
    try:
        return f"{float(value) * 100:.2f}%"
    except (TypeError, ValueError):
        return "未知"


def _first_value(row: dict[str, Any], *names: str) -> Any:
    """Return the first present value from common LLM-generated aliases."""
    for name in names:
        if name in row:
            return row.get(name)
    return None


def build_direct_answer(question: str, rows: list[dict[str, Any]]) -> str:
    """Answer common business questions directly before asking the LLM for advice."""
    text = question.lower()
    if rows and any(keyword in text for keyword in ("配送", "delivery", "延迟", "late", "准时")):
        overall = next((row for row in rows if row.get("customer_state") == "ALL"), None)
        states = [row for row in rows if row.get("customer_state") != "ALL"]
        worst = states[:5]
        overall_part = (
            f"平台整体准时交付率为 {_percent(overall.get('on_time_rate'))}，"
            f"延迟率为 {_percent(overall.get('late_rate'))}，"
            f"平均配送时长约 {overall.get('avg_delivery_days')} 天。"
            if overall
            else "平台整体准时率暂无可用汇总。"
        )
        worst_part = "延迟最严重的州：" + "；".join(
            f"{row.get('customer_state')} 延迟率 {_percent(row.get('late_rate'))}，延迟订单 {row.get('late_orders')} 单，平均 {row.get('avg_delivery_days')} 天"
            for row in worst
        )
        return f"{overall_part} {worst_part}"
    return ""


def build_direct_answer_from_results(question: str, results: dict[str, QueryResult]) -> str:
    """Build a data-grounded direct answer for required verification questions."""
    text = question.lower()
    all_results = list(results.values())
    is_strategy = any(keyword in text for keyword in ("策略", "建议", "方案", "降低", "改进", "3个月", "三大"))
    on_time_result = next((result for result in all_results if "overall_on_time_rate" in result.columns or "on_time_rate" in result.columns), None)
    late_state_result = next((result for result in all_results if {"customer_state", "late_rate"}.issubset(result.columns)), None)
    payment_result = next((result for result in all_results if "payment_type" in result.columns and any(column in result.columns for column in ("payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count"))), None)
    avg_installment_result = next((result for result in all_results if {"payment_type", "avg_installments"}.issubset(result.columns)), None)
    monthly_result = next((result for result in all_results if {"year_month", "total_gmv"}.issubset(result.columns)), None)
    state_sales_result = next((result for result in all_results if "customer_state" in result.columns and any(column in result.columns for column in ("total_gmv", "total_sales"))), None)
    weekly_result = next((result for result in all_results if {"week_start", "total_gmv"}.issubset(result.columns)), None)
    review_result = next((result for result in all_results if "product_category_name" in result.columns and any(column in result.columns for column in ("negative_rate", "bad_review_rate"))), None)
    seller_result = next((result for result in all_results if "seller_id" in result.columns and any(column in result.columns for column in ("avg_review_score", "negative_rate"))), None)
    delivery_duration_result = next((result for result in all_results if "customer_state" in result.columns and any(column in result.columns for column in ("avg_delivery_days", "state_avg_days"))), None)

    if is_strategy:
        return "已基于真实查询结果综合销售、配送、评价、卖家和商品维度，三个月内应优先处理高延迟地区、低评分卖家/品类和影响体验的履约问题；具体执行建议见下方大模型建议。"
    if state_sales_result and state_sales_result.rows and (payment_result or late_state_result or delivery_duration_result):
        top_state = state_sales_result.rows[0]
        state = top_state.get("customer_state")
        delivery_row: dict[str, Any] = {}
        if delivery_duration_result:
            delivery_row = next((row for row in delivery_duration_result.rows if row.get("customer_state") == state), {})
        if not delivery_row and late_state_result:
            delivery_row = next((row for row in late_state_result.rows if row.get("customer_state") == state), {})
        if not delivery_row and on_time_result and on_time_result.rows:
            delivery_row = on_time_result.rows[0]
        payment_row = payment_result.rows[0] if payment_result and payment_result.rows else {}
        on_time_rate = _first_value(delivery_row, "on_time_rate")
        late_rate = _first_value(delivery_row, "late_rate")
        if on_time_rate is None and late_rate is not None:
            try:
                on_time_rate = 1 - float(late_rate)
            except (TypeError, ValueError):
                on_time_rate = None
        return (
            f"销售额最高的州是 {state}，GMV约 {float(_first_value(top_state, 'total_gmv', 'total_sales') or 0):,.2f}；"
            f"该州准时交付率为 {_percent(on_time_rate)}；"
            f"最受欢迎支付方式是 {payment_row.get('payment_type', '见SQL结果')}。"
        )
    if on_time_result and on_time_result.rows:
        overall = on_time_result.rows[0]
        states = late_state_result.rows[:5] if late_state_result else []
        state_part = "；".join(
            f"{row.get('customer_state')} 延迟率 {_percent(row.get('late_rate'))}"
            for row in states
        )
        on_time_rate = overall.get("overall_on_time_rate", overall.get("on_time_rate"))
        late_rate = overall.get("overall_late_rate")
        if late_rate is None:
            try:
                late_rate = 1 - float(on_time_rate)
            except (TypeError, ValueError):
                late_rate = None
        return f"平台整体准时交付率为 {_percent(on_time_rate)}，延迟率为 {_percent(late_rate)}。延迟最严重州：{state_part}。"
    if payment_result and payment_result.rows:
        top = payment_result.rows[0]
        count = _first_value(top, "payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count")
        avg = _first_value(top, "avg_installments", "average_installments", "avg_payment_installments")
        if avg is None and avg_installment_result:
            avg_row = next((row for row in avg_installment_result.rows if row.get("payment_type") == top.get("payment_type")), avg_installment_result.rows[0] if avg_installment_result.rows else {})
            avg = _first_value(avg_row, "avg_installments", "average_installments", "avg_payment_installments")
        return f"最受欢迎的支付方式是 {top.get('payment_type')}，交易数 {count}，平均分期数约 {avg if avg is not None else '见SQL结果'}。"
    if monthly_result and monthly_result.rows:
        total_gmv = sum(float(row.get("total_gmv") or 0) for row in monthly_result.rows)
        state_part = ""
        if state_sales_result and state_sales_result.rows:
            top = state_sales_result.rows[0]
            state_part = f"州排名第一为 {top.get('customer_state')}，GMV约 {float(_first_value(top, 'total_gmv', 'total_sales') or 0):,.2f}。"
        return f"查询期GMV合计约 {total_gmv:,.2f}，已返回月度趋势。{state_part}"
    if weekly_result and weekly_result.rows:
        return f"已基于 {len(weekly_result.rows)} 周真实GMV序列生成未来6周预测，预测值和置信区间见预测图表。"
    if delivery_duration_result and seller_result and delivery_duration_result.rows and seller_result.rows:
        state = delivery_duration_result.rows[0]
        seller = seller_result.rows[0]
        return (
            f"平均配送时长偏高的重点州包括 {state.get('customer_state')}，平均约 {float(_first_value(state, 'avg_delivery_days', 'state_avg_days') or 0):.2f} 天；"
            f"高差评风险卖家代表为 {seller.get('seller_id')}，评分或差评指标见SQL结果。"
        )
    if review_result and review_result.rows:
        top = review_result.rows[0]
        negative_rate = _first_value(top, "negative_rate", "bad_review_rate")
        negative_reviews = _first_value(top, "negative_reviews", "bad_reviews", "low_score_reviews")
        return f"差评风险最高品类为 {top.get('product_category_name')}，差评率 {_percent(negative_rate)}，差评数 {negative_reviews}。"
    weight_result = next((result for result in all_results if any(column in result.columns for column in ("avg_weight_g", "product_weight_g")) and any(column in result.columns for column in ("avg_freight", "freight_value"))), None)
    if weight_result and weight_result.rows:
        return "已按重量区间与配送状态返回平均重量、体积、运费和订单量，可用于判断重量/尺寸与运费的关系。"
    if "delivery_performance" in results:
        answer = build_direct_answer(question, results["delivery_performance"].rows)
        if answer:
            return answer
    if "monthly_sales_2017" in results and "state_sales_2017" in results:
        months = results["monthly_sales_2017"].rows
        states = results["state_sales_2017"].rows
        total_gmv = sum(float(row.get("total_gmv") or 0) for row in months)
        top_state = states[0] if states else {}
        return (
            f"2017年GMV合计约 {total_gmv:,.2f}，月度趋势已按12个月返回；"
            f"州排名第一为 {top_state.get('customer_state')}，GMV约 {float(top_state.get('total_gmv') or 0):,.2f}。"
        )
    if "state_sales_2017" in results and "delivery_2017" in results and "payment_distribution" in results:
        top_state = results["state_sales_2017"].rows[0] if results["state_sales_2017"].rows else {}
        state = top_state.get("customer_state")
        delivery = next((row for row in results["delivery_2017"].rows if row.get("customer_state") == state), {})
        payment = results["payment_distribution"].rows[0] if results["payment_distribution"].rows else {}
        return (
            f"2017年销售额最高的州是 {state}，GMV约 {float(top_state.get('total_gmv') or 0):,.2f}；"
            f"该州准时交付率为 {_percent(delivery.get('on_time_rate'))}；"
            f"最受欢迎支付方式是 {payment.get('payment_type')}。"
        )
    if "payment_distribution" in results:
        rows = results["payment_distribution"].rows
        top = rows[0] if rows else {}
        count = _first_value(top, "payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count")
        avg = _first_value(top, "avg_installments", "average_installments", "avg_payment_installments")
        return f"最受欢迎的支付方式是 {top.get('payment_type')}，交易数 {count}；其平均分期数约 {avg if avg is not None else '未知'}。"
    if "weight_freight" in results:
        rows = results["weight_freight"].rows
        return "重量和体积越大的分组平均运费通常越高；结果已按重量区间和配送状态返回，可用于气泡散点图查看订单量差异。" if rows else ""
    if "review_category" in results:
        top = results["review_category"].rows[0] if results["review_category"].rows else {}
        return (
            f"差评风险最高品类为 {top.get('product_category_name')}，"
            f"差评率 {_percent(_first_value(top, 'negative_rate', 'bad_review_rate'))}，差评数 {_first_value(top, 'negative_reviews', 'bad_reviews', 'low_score_reviews')}。"
        )
    if "state_sales" in results:
        top = results["state_sales"].rows[0] if results["state_sales"].rows else {}
        return f"销售额最高的州为 {top.get('customer_state')}，GMV约 {float(top.get('total_gmv') or 0):,.2f}，订单数 {top.get('total_orders')}。"
    if {"monthly_sales", "delivery_performance", "review_category"}.issubset(results):
        delivery = results["delivery_performance"].rows[0] if results["delivery_performance"].rows else {}
        review = results["review_category"].rows[0] if results["review_category"].rows else {}
        return (
            "平台三个月优先改进应聚焦三件事："
            f"先治理 {delivery.get('customer_state')} 等高延迟州，"
            f"再处理 {review.get('product_category_name')} 等高差评品类，"
            "同时围绕主流支付方式优化结算与分期体验。"
        )
    return ""


def summarize_rows(rows: list[dict[str, Any]], columns: list[str]) -> str:
    """Create a compact Chinese data summary from query rows."""
    if not rows:
        return "查询成功，但结果为空。"
    parts = [f"返回 {len(rows)} 行，字段：{', '.join(columns)}。"]
    numeric_columns: list[str] = []
    for column in columns:
        if column == "sort_order":
            continue
        values = []
        for row in rows:
            try:
                if row[column] is not None and row[column] != "":
                    values.append(float(row[column]))
            except (TypeError, ValueError):
                pass
        if values and len(values) >= max(2, len(rows) // 3):
            numeric_columns.append(column)
            parts.append(f"{column} 均值 {mean(values):.2f}，最大 {max(values):.2f}，最小 {min(values):.2f}。")
        if len(numeric_columns) >= 3:
            break
    first = rows[0]
    parts.append("首行样例：" + ", ".join(f"{key}={first[key]}" for key in columns[:5]))
    return " ".join(parts)


def analyze_question(question: str) -> DataAnalysis:
    """Draft, route, execute, and summarize a business question."""
    tasks = draft_tasks(question)
    results: dict[str, QueryResult] = {}
    routes: dict[str, QueryRoute] = {}
    for task in tasks:
        results[task.name] = run_query(task.sql)
        routes[task.name] = decide_query_route(task.sql)
    primary = tasks[0]
    result = results[primary.name]
    route = routes[primary.name]
    summaries = [
        f"{task.purpose}：{summarize_rows(results[task.name].rows, results[task.name].columns)}"
        for task in tasks
    ]
    direct_answer = build_direct_answer_from_results(question, results)
    return DataAnalysis(
        question=question,
        sql=primary.sql,
        tasks=tasks,
        route=route,
        routes=routes,
        result=result,
        results=results,
        summary="\n".join(summaries),
        direct_answer=direct_answer,
    )
