"""DataAnalyst agent with view-first SQL routing and local execution."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from statistics import mean
from typing import Any

from config.prompts import DATA_ANALYST_SYSTEM_PROMPT
from utils.llm_client import chat_completion
from utils.local_store import QueryResult, run_query
from utils.query_router import QueryRoute, decide_query_route
from utils.schema import BASE_TABLES, render_schema_context


@dataclass(frozen=True)
class AnalysisDraft:
    """A safe SQL draft and routing metadata."""

    sql: str
    route: QueryRoute
    schema_context: str


@dataclass(frozen=True)
class QueryTask:
    """One SQL task planned by the DataAnalyst agent."""

    name: str
    sql: str
    purpose: str


DANGEROUS_SQL_PATTERN = re.compile(
    r"\b(insert|update|delete|drop|alter|create|replace|truncate|attach|detach|pragma|vacuum)\b",
    re.IGNORECASE,
)


def _extract_json_object(content: str) -> dict[str, Any]:
    """Parse a JSON object from the LLM response and fail loudly on invalid output."""
    cleaned = content.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start < 0 or end < start:
        raise ValueError("大模型未返回 JSON 对象，无法生成 SQL 任务")
    try:
        parsed = json.loads(cleaned[start : end + 1])
    except json.JSONDecodeError as exc:
        raise ValueError(f"大模型 SQL 计划 JSON 解析失败：{exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("大模型 SQL 计划不是 JSON 对象")
    return parsed


def _normalize_sql(sql: str) -> str:
    """修正常见的只读 SQL 方言差异，避免合法意图被 SQLite 语法细节拦住。"""
    normalized = sql.strip().rstrip(";")
    percentile_pattern = re.compile(
        r"\(\s*select\s+percentile_cont\((0?\.\d+|1(?:\.0+)?)\)\s+within\s+group\s*"
        r"\(\s*order\s+by\s+([A-Za-z_][A-Za-z0-9_.]*)\s*\)\s+from\s+([A-Za-z_][A-Za-z0-9_]*)\s+"
        r"where\s+(.+?)\)\s+as\s+([A-Za-z_][A-Za-z0-9_]*)",
        flags=re.IGNORECASE | re.DOTALL,
    )

    def _replace_percentile(match: re.Match[str]) -> str:
        percentile, order_column, table_name, where_clause, alias = match.groups()
        where_clause = where_clause.strip()
        return (
            f"(SELECT {order_column} FROM {table_name} WHERE {where_clause} "
            f"ORDER BY {order_column} LIMIT 1 OFFSET ("
            f"SELECT CAST((COUNT(*) - 1) * {float(percentile):.4f} AS INTEGER) "
            f"FROM {table_name} WHERE {where_clause})) AS {alias}"
        )

    normalized = percentile_pattern.sub(_replace_percentile, normalized)
    cte_match = re.match(
        r"^\s*with\s+([A-Za-z_][A-Za-z0-9_]*)\s+as\s*\(\s*(select\b.+?\border\s+by\b.+?\blimit\s+\d+)\s+union\s+all\s+(select\b.+?\border\s+by\b.+?\blimit\s+\d+)\s*\)\s+(select\b.+)$",
        normalized,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if cte_match:
        name, left, right, outer = cte_match.groups()
        return f"WITH {name} AS (SELECT * FROM ({left.strip()}) AS union_part_1 UNION ALL SELECT * FROM ({right.strip()}) AS union_part_2) {outer.strip()}"
    parts = re.split(r"\s+union\s+all\s+", normalized, flags=re.IGNORECASE)
    if (
        len(parts) == 2
        and all(part.strip().lower().startswith("select") for part in parts)
        and all(re.search(r"\border\s+by\b", part, flags=re.IGNORECASE) for part in parts)
    ):
        left, right = (part.strip() for part in parts)
        return f"SELECT * FROM ({left}) AS union_part_1 UNION ALL SELECT * FROM ({right}) AS union_part_2"
    return normalized


def _validate_sql(sql: str) -> str:
    """Allow only read-only SELECT/WITH statements generated by the LLM."""
    normalized = _normalize_sql(sql)
    lowered = normalized.lower()
    if not (lowered.startswith("select") or lowered.startswith("with")):
        raise ValueError(f"大模型生成了非只读 SQL：{sql}")
    if DANGEROUS_SQL_PATTERN.search(normalized):
        raise ValueError(f"大模型生成了危险 SQL：{sql}")
    if ";" in normalized:
        raise ValueError("大模型一次只能返回一条 SQL")
    if not re.search(r"\blimit\s+\d+\b", lowered):
        normalized = f"{normalized} LIMIT 200"
    return normalized


def _split_sql_statements(sql: str) -> list[str]:
    """拆开模型误放在同一个任务里的多条只读 SQL。"""
    cleaned = sql.strip()
    if ";" not in cleaned:
        return [cleaned] if cleaned else []
    statements: list[str] = []
    current: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(cleaned):
        char = cleaned[index]
        current.append(char)
        if quote:
            if char == quote:
                next_char = cleaned[index + 1] if index + 1 < len(cleaned) else ""
                if next_char == quote:
                    current.append(next_char)
                    index += 1
                else:
                    quote = None
        elif char in ("'", '"'):
            quote = char
        elif char == ";":
            statement = "".join(current).strip().rstrip(";").strip()
            if statement:
                statements.append(statement)
            current = []
        index += 1
    tail = "".join(current).strip().rstrip(";").strip()
    if tail:
        statements.append(tail)
    return statements


def _plan_context_json(plan_context: dict[str, Any] | None) -> str:
    """Serialize the Orchestrator plan so SQL planning can follow agent-level intent."""
    if not plan_context:
        return "无"
    return json.dumps(plan_context, ensure_ascii=False, indent=2)


def _plan_strings(plan_context: dict[str, Any] | None) -> list[str]:
    """Collect planner metrics/views/chart hints for guardrail checks."""
    if not plan_context:
        return []
    values: list[str] = []
    for key in ("analysis_type", "intent", "followup_reference", "reasoning_summary"):
        if plan_context.get(key):
            values.append(str(plan_context[key]))
    for key in ("metrics", "dimensions", "required_views"):
        raw = plan_context.get(key)
        if isinstance(raw, (list, tuple)):
            values.extend(str(item) for item in raw)
    for item in plan_context.get("chart_requirements") or []:
        if isinstance(item, dict):
            values.extend(str(value) for value in item.values() if value)
    return values


def plan_tasks_with_llm(question: str, plan_context: dict[str, Any] | None = None) -> tuple[QueryTask, ...]:
    """Use the configured remote LLM as the runtime SQL planner.

    这里不做本地模板兜底：模型不可用、JSON 非法或 SQL 非只读都会向上抛错，
    让前端真实展示问题，而不是用写死 SQL 制造完成假象。
    """
    allowed_base_tables = ", ".join(sorted(BASE_TABLES))
    prompt = f"""
用户问题：
{question}

数据字典：
{render_schema_context()}

规划要求：
1. 你是数据分析 Agent，需要把问题拆成 1 到 6 个 SQL 任务。
2. 优先使用 mv_* 预聚合表；只有视图不能覆盖时才 JOIN 基础表。
3. 所有 SQL 必须是 SQLite 兼容的只读 SELECT 或 WITH 查询。
4. 时间使用 substr(timestamp, 1, 7) 或 date/strftime；百分比字段返回 0-1 小数。
5. 需要预测未来6周时，请至少返回 mv_weekly_sales 的 week_start,total_gmv 序列。
6. 地图/地域问题优先使用 mv_state_geo；差评原因优先使用 mv_review_category_perf；重量运费优先使用 mv_weight_freight。
7. 基础表只允许这些：{allowed_base_tables}。
8. 不要使用 PERCENTILE_CONT、WITHIN GROUP、DATE_TRUNC、INTERVAL 等非 SQLite 语法；需要分位数时请用 ORDER BY + LIMIT/OFFSET 近似。

只返回 JSON，不要 Markdown。格式：
{{
  "tasks": [
    {{"name": "short_snake_case", "purpose": "中文用途", "sql": "SELECT ..."}}
  ]
}}
""".strip()
    if plan_context:
        prompt = f"协调器结构化计划：\n{_plan_context_json(plan_context)}\n\n{prompt}"
    response = chat_completion(DATA_ANALYST_SYSTEM_PROMPT, prompt, max_tokens=1800)
    payload = _extract_json_object(response.content)
    raw_tasks = payload.get("tasks")
    if not isinstance(raw_tasks, list) or not raw_tasks:
        raise ValueError("大模型 SQL 计划缺少 tasks")
    tasks: list[QueryTask] = []
    for index, raw_task in enumerate(raw_tasks[:6], start=1):
        if not isinstance(raw_task, dict):
            raise ValueError("大模型 SQL 任务格式错误")
        raw_sql = str(raw_task.get("sql") or "").strip()
        if not raw_sql:
            raise ValueError("大模型 SQL 任务缺少 sql")
        name = str(raw_task.get("name") or f"task_{index}").strip()
        purpose = str(raw_task.get("purpose") or name).strip()
        statements = _split_sql_statements(raw_sql)
        for statement_index, statement in enumerate(statements, start=1):
            task_name = name if len(statements) == 1 else f"{name}_{statement_index}"
            tasks.append(QueryTask(name=task_name, sql=_validate_sql(statement), purpose=purpose))
            if len(tasks) >= 6:
                break
        if len(tasks) >= 6:
            break
    return tuple(tasks)


def repair_tasks_with_llm(question: str, failed_tasks: tuple[QueryTask, ...], error: str, plan_context: dict[str, Any] | None = None) -> tuple[QueryTask, ...]:
    """Ask the remote LLM to repair invalid SQL once execution exposes an error."""
    prompt = f"""
用户问题：
{question}

数据字典：
{render_schema_context()}

上一轮 SQL 任务：
{json.dumps([{"name": task.name, "purpose": task.purpose, "sql": task.sql} for task in failed_tasks], ensure_ascii=False, indent=2)}

执行错误：
{error}

请修复 SQL。要求：
1. 仍然拆成 1 到 6 个 SQL 任务。
2. 优先使用 mv_* 预聚合表。
3. 所有 SQL 必须是 SQLite 兼容的只读 SELECT 或 WITH。
4. 不要引用不存在的表别名或字段。
5. 不要使用 PERCENTILE_CONT、WITHIN GROUP、DATE_TRUNC、INTERVAL 等非 SQLite 语法；需要分位数时请用 ORDER BY + LIMIT/OFFSET 近似。

只返回 JSON，不要 Markdown。格式：
{{
  "tasks": [
    {{"name": "short_snake_case", "purpose": "中文用途", "sql": "SELECT ..."}}
  ]
}}
""".strip()
    if plan_context:
        prompt = f"协调器结构化计划：\n{_plan_context_json(plan_context)}\n\n{prompt}"
    response = chat_completion(DATA_ANALYST_SYSTEM_PROMPT, prompt, max_tokens=1800)
    payload = _extract_json_object(response.content)
    raw_tasks = payload.get("tasks")
    if not isinstance(raw_tasks, list) or not raw_tasks:
        raise ValueError("大模型 SQL 修复结果缺少 tasks")
    tasks: list[QueryTask] = []
    for index, raw_task in enumerate(raw_tasks[:6], start=1):
        if not isinstance(raw_task, dict):
            raise ValueError("大模型 SQL 修复任务格式错误")
        raw_sql = str(raw_task.get("sql") or "").strip()
        if not raw_sql:
            raise ValueError("大模型 SQL 修复任务缺少 sql")
        name = str(raw_task.get("name") or f"repaired_task_{index}").strip()
        purpose = str(raw_task.get("purpose") or name).strip()
        statements = _split_sql_statements(raw_sql)
        for statement_index, statement in enumerate(statements, start=1):
            task_name = name if len(statements) == 1 else f"{name}_{statement_index}"
            tasks.append(QueryTask(name=task_name, sql=_validate_sql(statement), purpose=purpose))
            if len(tasks) >= 6:
                break
        if len(tasks) >= 6:
            break
    return tuple(tasks)


@dataclass(frozen=True)
class DataAnalysis:
    """Executed analysis output shared with downstream agents."""

    question: str
    sql: str
    tasks: tuple[QueryTask, ...]
    route: QueryRoute
    routes: dict[str, QueryRoute]
    result: QueryResult
    results: dict[str, QueryResult]
    summary: str
    direct_answer: str


def draft_tasks(question: str, plan_context: dict[str, Any] | None = None) -> tuple[QueryTask, ...]:
    """Ask the real LLM to plan view-first SQL tasks for the user question."""
    return plan_tasks_with_llm(question, plan_context=plan_context)


def draft_sql(question: str) -> AnalysisDraft:
    """Draft the primary view-first SQL statement for compatibility with tests."""
    sql = draft_tasks(question)[0].sql
    return AnalysisDraft(sql=sql, route=decide_query_route(sql), schema_context=render_schema_context())


def _percent(value: object) -> str:
    try:
        return f"{float(value) * 100:.2f}%"
    except (TypeError, ValueError):
        return "未知"


def _first_value(row: dict[str, Any], *names: str) -> Any:
    """Return the first present value from common LLM-generated aliases."""
    for name in names:
        if name in row:
            return row.get(name)
    return None


def build_direct_answer(question: str, rows: list[dict[str, Any]]) -> str:
    """Answer common business questions directly before asking the LLM for advice."""
    text = question.lower()
    if rows and any(keyword in text for keyword in ("配送", "delivery", "延迟", "late", "准时")):
        overall = next((row for row in rows if row.get("customer_state") == "ALL"), None)
        states = [row for row in rows if row.get("customer_state") != "ALL"]
        worst = states[:5]
        overall_part = (
            f"平台整体准时交付率为 {_percent(overall.get('on_time_rate'))}，"
            f"延迟率为 {_percent(overall.get('late_rate'))}，"
            f"平均配送时长约 {overall.get('avg_delivery_days')} 天。"
            if overall
            else "平台整体准时率暂无可用汇总。"
        )
        worst_part = "延迟最严重的州：" + "；".join(
            f"{row.get('customer_state')} 延迟率 {_percent(row.get('late_rate'))}，延迟订单 {row.get('late_orders')} 单，平均 {row.get('avg_delivery_days')} 天"
            for row in worst
        )
        return f"{overall_part} {worst_part}"
    return ""


def build_direct_answer_from_results(question: str, results: dict[str, QueryResult]) -> str:
    """Build a data-grounded direct answer for required verification questions."""
    text = question.lower()
    all_results = list(results.values())
    is_strategy = any(keyword in text for keyword in ("策略", "建议", "方案", "降低", "改进", "3个月", "三大"))
    is_delivery_focus = any(keyword in text for keyword in ("配送", "交付", "延迟", "准时", "物流", "履约", "风险热区", "delivery", "late", "on time", "on-time"))
    on_time_result = results.get("delivery_overall") or next(
        (
            result
            for result in all_results
            if "overall_on_time_rate" in result.columns or ("on_time_rate" in result.columns and "customer_state" not in result.columns)
        ),
        None,
    )
    late_state_result = results.get("delivery_by_state") or next((result for result in all_results if {"customer_state", "late_rate"}.issubset(result.columns)), None)
    payment_result = results.get("payment_summary") or next(
        (
            result
            for result in all_results
            if "payment_type" in result.columns
            and "payment_installments" not in result.columns
            and any(column in result.columns for column in ("payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count"))
        ),
        None,
    )
    avg_installment_result = next((result for result in all_results if {"payment_type", "avg_installments"}.issubset(result.columns)), None)
    monthly_result = results.get("monthly_sales_2017") or results.get("monthly_sales") or next((result for result in all_results if {"year_month", "total_gmv"}.issubset(result.columns)), None)
    state_sales_result = results.get("state_sales_2017") or results.get("state_sales") or next((result for result in all_results if "customer_state" in result.columns and any(column in result.columns for column in ("total_gmv", "total_sales", "total_orders", "avg_order_value"))), None)
    weekly_result = next((result for result in all_results if {"week_start", "total_gmv"}.issubset(result.columns)), None)
    category_result = results.get("category_sales") or next((result for result in all_results if "product_category_name" in result.columns and any(column in result.columns for column in ("total_gmv", "total_sales", "total_orders", "avg_order_value"))), None)
    review_result = results.get("review_category") or next((result for result in all_results if "product_category_name" in result.columns and any(column in result.columns for column in ("negative_rate", "bad_review_rate", "negative_reviews", "delay_complaints", "quality_complaints"))), None)
    seller_result = results.get("seller_review") or next((result for result in all_results if "seller_id" in result.columns and any(column in result.columns for column in ("avg_review_score", "negative_rate"))), None)
    delivery_duration_result = results.get("delivery_by_state") or next((result for result in all_results if "customer_state" in result.columns and any(column in result.columns for column in ("avg_delivery_days", "state_avg_days"))), None)
    weight_result = next((result for result in all_results if any(column in result.columns for column in ("avg_weight_g", "product_weight_g")) and any(column in result.columns for column in ("avg_freight", "freight_value"))), None)

    is_payment_focus = any(keyword in text for keyword in ("支付", "分期", "payment", "installment", "boleto", "credit"))
    is_review_focus = any(keyword in text for keyword in ("差评", "评分", "评价", "评论", "低分", "反馈", "review", "negative"))
    is_seller_focus = any(keyword in text for keyword in ("卖家", "seller"))
    is_weight_focus = any(keyword in text for keyword in ("重量", "尺寸", "体积", "运费", "运力成本", "weight", "freight"))
    is_category_focus = any(keyword in text for keyword in ("品类", "产品组", "category", "health_beauty"))
    is_forecast_focus = any(keyword in text for keyword in ("预测", "未来6周", "未来六周", "区间", "forecast"))

    if is_strategy:
        return "已基于真实查询结果综合销售、配送、评价、卖家和商品维度，三个月内应优先处理高延迟地区、低评分卖家/品类和影响体验的履约问题；具体执行建议见下方大模型建议。"
    if is_forecast_focus and weekly_result and weekly_result.rows:
        return f"已基于 {len(weekly_result.rows)} 周真实GMV序列生成未来6周预测，预测值、上下界区间和误差诊断见预测图表。"
    if state_sales_result and state_sales_result.rows and payment_result and (late_state_result or delivery_duration_result) and "州" in text:
        top_state = state_sales_result.rows[0]
        state = top_state.get("customer_state")
        delivery_row: dict[str, Any] = {}
        if delivery_duration_result:
            delivery_row = next((row for row in delivery_duration_result.rows if row.get("customer_state") == state), {})
        if not delivery_row and late_state_result:
            delivery_row = next((row for row in late_state_result.rows if row.get("customer_state") == state), {})
        payment_row = payment_result.rows[0] if payment_result and payment_result.rows else {}
        on_time_rate = _first_value(delivery_row, "on_time_rate")
        late_rate = _first_value(delivery_row, "late_rate")
        if on_time_rate is None and late_rate is not None:
            try:
                on_time_rate = 1 - float(late_rate)
            except (TypeError, ValueError):
                on_time_rate = None
        return (
            f"销售额最高的州是 {state}，GMV约 {float(_first_value(top_state, 'total_gmv', 'total_sales') or 0):,.2f}；"
            f"该州准时交付率为 {_percent(on_time_rate)}；"
            f"最受欢迎支付方式是 {payment_row.get('payment_type', '见SQL结果')}。"
        )
    if is_payment_focus and payment_result and payment_result.rows:
        top = payment_result.rows[0]
        count = _first_value(top, "payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count")
        avg = _first_value(top, "avg_installments", "average_installments", "avg_payment_installments")
        if avg is None and avg_installment_result:
            avg_row = next((row for row in avg_installment_result.rows if row.get("payment_type") == top.get("payment_type")), avg_installment_result.rows[0] if avg_installment_result.rows else {})
            avg = _first_value(avg_row, "avg_installments", "average_installments", "avg_payment_installments")
        return f"支付分布显示最主要方式是 {top.get('payment_type')}，交易数 {count}；平均分期数约 {avg if avg is not None else '见SQL结果'}，高分期和金额差异见热力图/SQL证据。"
    if is_seller_focus and seller_result and seller_result.rows:
        seller = seller_result.rows[0]
        state = seller.get("seller_state", seller.get("customer_state", "见SQL结果"))
        score = _first_value(seller, "avg_review_score")
        negative_rate = _first_value(seller, "negative_rate")
        metric = f"差评率 {_percent(negative_rate)}" if negative_rate is not None else f"平均评分 {score}"
        return f"需优先关注卖家 {seller.get('seller_id', '见SQL结果')}（州 {state}），其{metric}，订单数 {seller.get('total_orders', '见SQL结果')}。"
    if is_review_focus and review_result and review_result.rows:
        top = review_result.rows[0]
        delay_total = sum(int(_first_value(row, "delay_complaints") or 0) for row in review_result.rows)
        quality_total = sum(int(_first_value(row, "quality_complaints") or 0) for row in review_result.rows)
        reason_hint = f"整体看物流延迟投诉 {delay_total} 次、质量投诉 {quality_total} 次；" if delay_total or quality_total else ""
        negative_rate = _first_value(top, "negative_rate", "bad_review_rate")
        negative_reviews = _first_value(top, "negative_reviews", "bad_reviews", "low_score_reviews")
        return f"{reason_hint}差评风险最高品类为 {top.get('product_category_name')}，差评率 {_percent(negative_rate)}，差评数 {negative_reviews}。"
    if is_weight_focus and weight_result and weight_result.rows:
        top = weight_result.rows[0]
        return (
            f"已按重量/体积分组返回运费证据；样本中 {top.get('weight_bucket', '相关分组')} "
            f"平均重量约 {_first_value(top, 'avg_weight_g', 'product_weight_g') or '见SQL结果'}g，"
            f"平均运费约 {_first_value(top, 'avg_freight', 'freight_value') or '见SQL结果'}。"
        )
    if is_category_focus and category_result and category_result.rows:
        top = category_result.rows[0]
        review_row = review_result.rows[0] if review_result and review_result.rows else {}
        total_gmv = float(_first_value(top, "total_gmv", "total_sales") or 0)
        extra = f"；评分/差评证据显示 {review_row.get('product_category_name')} 差评率 {_percent(_first_value(review_row, 'negative_rate', 'bad_review_rate'))}" if review_row else ""
        return f"品类表现最高的是 {top.get('product_category_name')}，GMV约 {total_gmv:,.2f}，订单数 {top.get('total_orders', '见SQL结果')}{extra}。"
    if is_delivery_focus and (on_time_result or late_state_result) and not payment_result and not seller_result:
        overall = on_time_result.rows[0] if on_time_result and on_time_result.rows else {}
        states = late_state_result.rows[:5] if late_state_result else []
        state_part = "；".join(
            f"{row.get('customer_state')} 延迟率{_percent(row.get('late_rate'))}，延迟订单{row.get('late_orders', '见SQL结果')}"
            for row in states
        )
        on_time_rate = overall.get("overall_on_time_rate", overall.get("on_time_rate"))
        late_rate = overall.get("overall_late_rate")
        if late_rate is None and on_time_rate is not None:
            try:
                late_rate = 1 - float(on_time_rate)
            except (TypeError, ValueError):
                late_rate = None
        prefix = f"平台整体准时交付率为 {_percent(on_time_rate)}，延迟率为 {_percent(late_rate)}。" if overall else ""
        return f"{prefix}物流风险较高的州：{state_part}。"
    if state_sales_result and state_sales_result.rows and (payment_result or late_state_result or delivery_duration_result) and not seller_result:
        top_state = state_sales_result.rows[0]
        state = top_state.get("customer_state")
        delivery_row: dict[str, Any] = {}
        if delivery_duration_result:
            delivery_row = next((row for row in delivery_duration_result.rows if row.get("customer_state") == state), {})
        if not delivery_row and late_state_result:
            delivery_row = next((row for row in late_state_result.rows if row.get("customer_state") == state), {})
        if not delivery_row and on_time_result and on_time_result.rows:
            delivery_row = on_time_result.rows[0]
        payment_row = payment_result.rows[0] if payment_result and payment_result.rows else {}
        on_time_rate = _first_value(delivery_row, "on_time_rate")
        late_rate = _first_value(delivery_row, "late_rate")
        if on_time_rate is None and late_rate is not None:
            try:
                on_time_rate = 1 - float(late_rate)
            except (TypeError, ValueError):
                on_time_rate = None
        return (
            f"销售额最高的州是 {state}，GMV约 {float(_first_value(top_state, 'total_gmv', 'total_sales') or 0):,.2f}；"
            f"该州准时交付率为 {_percent(on_time_rate)}；"
            f"最受欢迎支付方式是 {payment_row.get('payment_type', '见SQL结果')}。"
        )
    if delivery_duration_result and seller_result and delivery_duration_result.rows and seller_result.rows:
        state = delivery_duration_result.rows[0]
        seller = seller_result.rows[0]
        seller_metric = _first_value(seller, "negative_rate", "avg_review_score")
        metric_label = "差评率" if "negative_rate" in seller else "平均评分"
        return (
            f"平均配送时长或延迟率偏高的重点州包括 {state.get('customer_state')}，"
            f"平均配送约 {float(_first_value(state, 'avg_delivery_days', 'state_avg_days') or 0):.2f} 天；"
            f"需优先复核卖家 {seller.get('seller_id')}，其{metric_label}为 {seller_metric}。"
        )
    if on_time_result and on_time_result.rows:
        overall = on_time_result.rows[0]
        states = late_state_result.rows[:5] if late_state_result else []
        state_part = "；".join(
            f"{row.get('customer_state')} 延迟率 {_percent(row.get('late_rate'))}"
            for row in states
        )
        on_time_rate = overall.get("overall_on_time_rate", overall.get("on_time_rate"))
        late_rate = overall.get("overall_late_rate")
        if late_rate is None:
            try:
                late_rate = 1 - float(on_time_rate)
            except (TypeError, ValueError):
                late_rate = None
        return f"平台整体准时交付率为 {_percent(on_time_rate)}，延迟率为 {_percent(late_rate)}。延迟最严重州：{state_part}。"
    if payment_result and payment_result.rows:
        top = payment_result.rows[0]
        count = _first_value(top, "payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count")
        avg = _first_value(top, "avg_installments", "average_installments", "avg_payment_installments")
        if avg is None and avg_installment_result:
            avg_row = next((row for row in avg_installment_result.rows if row.get("payment_type") == top.get("payment_type")), avg_installment_result.rows[0] if avg_installment_result.rows else {})
            avg = _first_value(avg_row, "avg_installments", "average_installments", "avg_payment_installments")
        return f"最受欢迎的支付方式是 {top.get('payment_type')}，交易数 {count}，平均分期数约 {avg if avg is not None else '见SQL结果'}。"
    if monthly_result and monthly_result.rows:
        total_gmv = sum(float(row.get("total_gmv") or 0) for row in monthly_result.rows)
        state_part = ""
        if state_sales_result and state_sales_result.rows:
            top = state_sales_result.rows[0]
            state_part = f"州排名第一为 {top.get('customer_state')}，GMV约 {float(_first_value(top, 'total_gmv', 'total_sales') or 0):,.2f}。"
        return f"查询期GMV合计约 {total_gmv:,.2f}，已返回月度趋势。{state_part}"
    if weekly_result and weekly_result.rows:
        return f"已基于 {len(weekly_result.rows)} 周真实GMV序列生成未来6周预测，预测值和置信区间见预测图表。"
    if state_sales_result and state_sales_result.rows:
        value_key = "total_gmv" if any(_first_value(row, "total_gmv", "total_sales") is not None for row in state_sales_result.rows) else "total_orders"
        sorted_rows = sorted(
            state_sales_result.rows,
            key=lambda row: float(_first_value(row, value_key, "total_sales") or 0),
            reverse=True,
        )
        top = sorted_rows[0]
        bottom = sorted_rows[-1] if len(sorted_rows) > 1 else {}
        top_gmv = float(_first_value(top, "total_gmv", "total_sales") or 0)
        if top_gmv:
            answer = f"销售表现最高的州是 {top.get('customer_state')}，GMV约 {top_gmv:,.2f}，订单数 {top.get('total_orders', '见SQL结果')}。"
        else:
            answer = f"订单量最高的州是 {top.get('customer_state')}，订单数 {top.get('total_orders', '见SQL结果')}，客单价约 {_first_value(top, 'avg_order_value', 'avg_price') or '见SQL结果'}。"
        if any(keyword in text for keyword in ("最低", "最差", "对比", "比较")) and bottom:
            bottom_gmv = float(_first_value(bottom, "total_gmv", "total_sales") or 0)
            if bottom_gmv:
                answer += f" 对比样本中最低的是 {bottom.get('customer_state')}，GMV约 {bottom_gmv:,.2f}，可结合图表和SQL查看差距。"
            else:
                answer += f" 对比样本中最低的是 {bottom.get('customer_state')}，订单数 {bottom.get('total_orders', '见SQL结果')}，可结合图表和SQL查看差距。"
        return answer
    if review_result and review_result.rows:
        top = review_result.rows[0]
        negative_rate = _first_value(top, "negative_rate", "bad_review_rate")
        negative_reviews = _first_value(top, "negative_reviews", "bad_reviews", "low_score_reviews")
        reason_fields = {
            "物流延迟": _first_value(top, "delay_complaints"),
            "质量问题": _first_value(top, "quality_complaints"),
            "错发/退换": _first_value(top, "wrong_item_complaints"),
            "客服/沟通": _first_value(top, "service_complaints"),
            "其他": _first_value(top, "other_complaints"),
        }
        ranked_reasons = sorted(
            ((name, int(value)) for name, value in reason_fields.items() if value not in (None, "")),
            key=lambda item: item[1],
            reverse=True,
        )
        reason_text = "，主要原因：" + "、".join(f"{name}{value}次" for name, value in ranked_reasons[:3]) if ranked_reasons else ""
        rate_text = f"差评率 {_percent(negative_rate)}，" if negative_rate is not None else ""
        return f"差评风险最高品类为 {top.get('product_category_name')}，{rate_text}差评数 {negative_reviews}{reason_text}。"
    if category_result and category_result.rows:
        top = category_result.rows[0]
        total_gmv = float(_first_value(top, "total_gmv", "total_sales") or 0)
        avg_order_value = _first_value(top, "avg_order_value", "avg_price")
        return (
            f"品类表现最高的是 {top.get('product_category_name')}，GMV约 {total_gmv:,.2f}，"
            f"订单数 {top.get('total_orders', '见SQL结果')}，客单价约 {avg_order_value if avg_order_value is not None else '见SQL结果'}。"
        )
    if weight_result and weight_result.rows:
        return "已按重量区间与配送状态返回平均重量、体积、运费和订单量，可用于判断重量/尺寸与运费的关系。"
    if "delivery_performance" in results:
        answer = build_direct_answer(question, results["delivery_performance"].rows)
        if answer:
            return answer
    if "monthly_sales_2017" in results and "state_sales_2017" in results:
        months = results["monthly_sales_2017"].rows
        states = results["state_sales_2017"].rows
        total_gmv = sum(float(row.get("total_gmv") or 0) for row in months)
        top_state = states[0] if states else {}
        return (
            f"2017年GMV合计约 {total_gmv:,.2f}，月度趋势已按12个月返回；"
            f"州排名第一为 {top_state.get('customer_state')}，GMV约 {float(top_state.get('total_gmv') or 0):,.2f}。"
        )
    if "state_sales_2017" in results and "delivery_2017" in results and "payment_distribution" in results:
        top_state = results["state_sales_2017"].rows[0] if results["state_sales_2017"].rows else {}
        state = top_state.get("customer_state")
        delivery = next((row for row in results["delivery_2017"].rows if row.get("customer_state") == state), {})
        payment = results["payment_distribution"].rows[0] if results["payment_distribution"].rows else {}
        return (
            f"2017年销售额最高的州是 {state}，GMV约 {float(top_state.get('total_gmv') or 0):,.2f}；"
            f"该州准时交付率为 {_percent(delivery.get('on_time_rate'))}；"
            f"最受欢迎支付方式是 {payment.get('payment_type')}。"
        )
    if "payment_distribution" in results:
        rows = results["payment_distribution"].rows
        top = rows[0] if rows else {}
        count = _first_value(top, "payment_count", "total_transactions", "transaction_count", "total_orders", "total_count", "count")
        avg = _first_value(top, "avg_installments", "average_installments", "avg_payment_installments")
        return f"最受欢迎的支付方式是 {top.get('payment_type')}，交易数 {count}；其平均分期数约 {avg if avg is not None else '未知'}。"
    if "weight_freight" in results:
        rows = results["weight_freight"].rows
        return "重量和体积越大的分组平均运费通常越高；结果已按重量区间和配送状态返回，可用于气泡散点图查看订单量差异。" if rows else ""
    if "review_category" in results:
        top = results["review_category"].rows[0] if results["review_category"].rows else {}
        return (
            f"差评风险最高品类为 {top.get('product_category_name')}，"
            f"差评率 {_percent(_first_value(top, 'negative_rate', 'bad_review_rate'))}，差评数 {_first_value(top, 'negative_reviews', 'bad_reviews', 'low_score_reviews')}。"
        )
    if "state_sales" in results:
        top = results["state_sales"].rows[0] if results["state_sales"].rows else {}
        return f"销售额最高的州为 {top.get('customer_state')}，GMV约 {float(top.get('total_gmv') or 0):,.2f}，订单数 {top.get('total_orders')}。"
    if {"monthly_sales", "delivery_performance", "review_category"}.issubset(results):
        delivery = results["delivery_performance"].rows[0] if results["delivery_performance"].rows else {}
        review = results["review_category"].rows[0] if results["review_category"].rows else {}
        return (
            "平台三个月优先改进应聚焦三件事："
            f"先治理 {delivery.get('customer_state')} 等高延迟州，"
            f"再处理 {review.get('product_category_name')} 等高差评品类，"
            "同时围绕主流支付方式优化结算与分期体验。"
        )
    return ""


SUPPLEMENTAL_TASKS: dict[str, QueryTask] = {
    "monthly_sales": QueryTask(
        "monthly_sales",
        "SELECT year_month, total_orders, total_gmv, avg_price, total_freight FROM mv_monthly_sales ORDER BY year_month LIMIT 120",
        "月度销售趋势与GMV走势",
    ),
    "monthly_sales_2017": QueryTask(
        "monthly_sales_2017",
        "SELECT year_month, total_orders, total_gmv, avg_price, total_freight FROM mv_monthly_sales WHERE year_month LIKE '2017-%' ORDER BY year_month LIMIT 12",
        "2017年月度GMV趋势",
    ),
    "weekly_sales": QueryTask(
        "weekly_sales",
        "SELECT week_start, total_orders, total_gmv, avg_order_value FROM mv_weekly_sales ORDER BY week_start LIMIT 160",
        "未来6周预测所需的真实周GMV序列",
    ),
    "state_sales": QueryTask(
        "state_sales",
        "SELECT customer_state, SUM(total_orders) AS total_orders, ROUND(SUM(total_gmv), 2) AS total_gmv, ROUND(SUM(total_gmv) / NULLIF(SUM(total_orders), 0), 2) AS avg_order_value FROM mv_state_sales GROUP BY customer_state ORDER BY total_gmv DESC LIMIT 27",
        "各州销售额、订单量和客单价排名",
    ),
    "state_sales_2017": QueryTask(
        "state_sales_2017",
        "SELECT customer_state, SUM(total_orders) AS total_orders, ROUND(SUM(total_gmv), 2) AS total_gmv, ROUND(SUM(total_gmv) / NULLIF(SUM(total_orders), 0), 2) AS avg_order_value FROM mv_state_sales WHERE year_month LIKE '2017-%' GROUP BY customer_state ORDER BY total_gmv DESC LIMIT 27",
        "2017年各州销售额、订单量和客单价排名",
    ),
    "state_geo_map": QueryTask(
        "state_geo_map",
        "SELECT customer_state, lat, lng, total_orders, total_gmv, avg_order_value FROM mv_state_geo WHERE lat IS NOT NULL AND lng IS NOT NULL ORDER BY total_gmv DESC LIMIT 27",
        "地图可视化所需的巴西州级经纬度与销售分布",
    ),
    "delivery_geo_map": QueryTask(
        "delivery_geo_map",
        """
        SELECT
          g.customer_state,
          g.lat,
          g.lng,
          d.total_orders,
          g.total_gmv,
          g.avg_order_value,
          d.avg_delivery_days,
          d.late_orders,
          d.late_rate,
          d.on_time_rate,
          'delivery_late' AS map_metric
        FROM mv_state_geo g
        JOIN (
          SELECT
            customer_state,
            SUM(total_orders) AS total_orders,
            ROUND(SUM(avg_delivery_days * total_orders) / NULLIF(SUM(total_orders), 0), 2) AS avg_delivery_days,
            SUM(late_orders) AS late_orders,
            ROUND(1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS late_rate,
            ROUND(1.0 - 1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS on_time_rate
          FROM mv_delivery_perf
          GROUP BY customer_state
        ) d ON g.customer_state = d.customer_state
        WHERE g.lat IS NOT NULL AND g.lng IS NOT NULL
        ORDER BY d.late_rate DESC, d.late_orders DESC
        LIMIT 27
        """,
        "地图可视化所需的州级经纬度与配送延迟指标",
    ),
    "on_time_geo_map": QueryTask(
        "on_time_geo_map",
        """
        SELECT
          g.customer_state,
          g.lat,
          g.lng,
          d.total_orders,
          g.total_gmv,
          g.avg_order_value,
          d.avg_delivery_days,
          d.late_orders,
          d.late_rate,
          d.on_time_rate,
          'delivery_on_time' AS map_metric
        FROM mv_state_geo g
        JOIN (
          SELECT
            customer_state,
            SUM(total_orders) AS total_orders,
            ROUND(SUM(avg_delivery_days * total_orders) / NULLIF(SUM(total_orders), 0), 2) AS avg_delivery_days,
            SUM(late_orders) AS late_orders,
            ROUND(1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS late_rate,
            ROUND(1.0 - 1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS on_time_rate
          FROM mv_delivery_perf
          GROUP BY customer_state
        ) d ON g.customer_state = d.customer_state
        WHERE g.lat IS NOT NULL AND g.lng IS NOT NULL
        ORDER BY d.on_time_rate ASC, d.total_orders DESC
        LIMIT 27
        """,
        "地图可视化所需的州级经纬度与准时交付率指标",
    ),
    "delivery_overall": QueryTask(
        "delivery_overall",
        "SELECT SUM(total_orders) AS total_orders, ROUND(1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS overall_late_rate, ROUND(1.0 - 1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS overall_on_time_rate, ROUND(SUM(avg_delivery_days * total_orders) / NULLIF(SUM(total_orders), 0), 2) AS avg_delivery_days FROM mv_delivery_perf",
        "平台整体准时率、延迟率和平均配送时长",
    ),
    "delivery_by_state": QueryTask(
        "delivery_by_state",
        "SELECT customer_state, SUM(total_orders) AS total_orders, ROUND(SUM(avg_delivery_days * total_orders) / NULLIF(SUM(total_orders), 0), 2) AS avg_delivery_days, SUM(late_orders) AS late_orders, ROUND(1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS late_rate, ROUND(1.0 - 1.0 * SUM(late_orders) / NULLIF(SUM(total_orders), 0), 4) AS on_time_rate FROM mv_delivery_perf GROUP BY customer_state ORDER BY late_rate DESC, total_orders DESC LIMIT 27",
        "各州配送延迟率和准时率对比",
    ),
    "payment_summary": QueryTask(
        "payment_summary",
        "SELECT payment_type, SUM(payment_count) AS payment_count, ROUND(SUM(payment_value), 2) AS payment_value, ROUND(SUM(payment_installments * payment_count) / NULLIF(SUM(payment_count), 0), 2) AS avg_installments FROM mv_payment_dist GROUP BY payment_type ORDER BY payment_count DESC LIMIT 10",
        "支付方式受欢迎程度和平均分期数",
    ),
    "payment_heatmap": QueryTask(
        "payment_heatmap",
        "SELECT payment_type, payment_installments, SUM(payment_count) AS payment_count, ROUND(SUM(payment_value), 2) AS payment_value FROM mv_payment_dist GROUP BY payment_type, payment_installments ORDER BY payment_type, payment_installments LIMIT 120",
        "支付方式与分期数交叉热力矩阵",
    ),
    "category_sales": QueryTask(
        "category_sales",
        "SELECT product_category_name, SUM(total_orders) AS total_orders, ROUND(SUM(total_gmv), 2) AS total_gmv FROM mv_category_sales GROUP BY product_category_name ORDER BY total_gmv DESC LIMIT 20",
        "Top品类销售额和订单量排名",
    ),
    "review_category": QueryTask(
        "review_category",
        "SELECT product_category_name, total_reviews, avg_review_score, negative_reviews, negative_rate, delay_complaints, quality_complaints, wrong_item_complaints, service_complaints, other_complaints FROM mv_review_category_perf ORDER BY negative_reviews DESC, negative_rate DESC LIMIT 20",
        "Top差评品类及物流、质量、错发、客服和其他原因分类",
    ),
    "seller_review": QueryTask(
        "seller_review",
        "SELECT seller_id, seller_state, SUM(total_orders) AS total_orders, ROUND(SUM(total_gmv), 2) AS total_gmv, ROUND(AVG(avg_review_score), 2) AS avg_review_score FROM mv_seller_perf GROUP BY seller_id, seller_state HAVING total_orders >= 3 ORDER BY avg_review_score ASC, total_orders DESC LIMIT 20",
        "低评分卖家定位和卖家绩效诊断",
    ),
    "seller_geo_map": QueryTask(
        "seller_geo_map",
        """
        SELECT
          g.customer_state,
          g.lat,
          g.lng,
          s.total_orders,
          s.total_gmv,
          s.avg_review_score,
          'seller_review_risk' AS map_metric
        FROM mv_state_geo g
        JOIN (
          SELECT
            seller_state AS customer_state,
            SUM(total_orders) AS total_orders,
            ROUND(SUM(total_gmv), 2) AS total_gmv,
            ROUND(AVG(avg_review_score), 2) AS avg_review_score
          FROM mv_seller_perf
          GROUP BY seller_state
        ) s ON g.customer_state = s.customer_state
        WHERE g.lat IS NOT NULL AND g.lng IS NOT NULL
        ORDER BY s.avg_review_score ASC, s.total_orders DESC
        LIMIT 27
        """,
        "地图可视化所需的州级经纬度与卖家评分风险指标",
    ),
    "weight_freight": QueryTask(
        "weight_freight",
        "SELECT weight_bucket, delivery_status, order_count, avg_weight_g, avg_volume_cm3, avg_freight, avg_price FROM mv_weight_freight ORDER BY avg_weight_g, delivery_status LIMIT 40",
        "商品重量/体积与运费关系",
    ),
}


def _append_task(tasks: tuple[QueryTask, ...], key: str) -> tuple[QueryTask, ...]:
    task = SUPPLEMENTAL_TASKS[key]
    if any(existing.name == task.name for existing in tasks):
        return tasks
    if any(existing.sql.strip().lower() == task.sql.strip().lower() for existing in tasks):
        return tasks
    return (*tasks, task)


def _prepend_task(tasks: tuple[QueryTask, ...], key: str) -> tuple[QueryTask, ...]:
    """Put the most relevant map evidence first so the dashboard opens on it."""
    task = SUPPLEMENTAL_TASKS[key]
    if any(existing.name == task.name for existing in tasks):
        return tasks
    if any(existing.sql.strip().lower() == task.sql.strip().lower() for existing in tasks):
        return tasks
    return (task, *tasks)


def _geo_task_key(question: str = "", plan_context: dict[str, Any] | None = None) -> str:
    """Choose the state-level map evidence that matches the user's business metric."""
    plan_text = " ".join(_plan_strings(plan_context)).lower()
    if any(metric in plan_text for metric in ("delivery_on_time_rate", "on_time_rate", "fulfillment_rate")):
        return "on_time_geo_map"
    if any(metric in plan_text for metric in ("delivery_late_rate", "late_rate", "delivery_delay", "logistics_risk")):
        return "delivery_geo_map"
    if any(metric in plan_text for metric in ("seller_review_risk", "seller_score", "review_risk")):
        return "seller_geo_map"
    if any(metric in plan_text for metric in ("sales_gmv", "total_gmv", "order_volume")):
        return "state_geo_map"

    text = question.lower()
    if any(keyword in text for keyword in ("准时", "履约", "on time", "on-time")):
        return "on_time_geo_map"
    if any(keyword in text for keyword in ("配送", "交付", "延迟", "late", "delivery", "瓶颈")):
        return "delivery_geo_map"
    if any(keyword in text for keyword in ("卖家", "评分", "差评", "review", "seller")):
        return "seller_geo_map"
    return "state_geo_map"


def _append_tasks_for_view(tasks: tuple[QueryTask, ...], view: str, plan_context: dict[str, Any] | None) -> tuple[QueryTask, ...]:
    """Translate planner-required views into evidence queries; this does not fabricate answers."""
    if view == "mv_monthly_sales":
        return _append_task(tasks, "monthly_sales")
    if view == "mv_weekly_sales":
        return _append_task(tasks, "weekly_sales")
    if view == "mv_state_sales":
        return _append_task(tasks, "state_sales")
    if view == "mv_state_geo":
        return _prepend_task(tasks, _geo_task_key(plan_context=plan_context))
    if view == "mv_delivery_perf":
        tasks = _append_task(tasks, "delivery_overall")
        return _append_task(tasks, "delivery_by_state")
    if view == "mv_payment_dist":
        tasks = _append_task(tasks, "payment_summary")
        return _append_task(tasks, "payment_heatmap")
    if view == "mv_category_sales":
        return _append_task(tasks, "category_sales")
    if view == "mv_review_category_perf":
        return _append_task(tasks, "review_category")
    if view == "mv_seller_perf":
        return _append_task(tasks, "seller_review")
    if view == "mv_weight_freight":
        return _append_task(tasks, "weight_freight")
    return tasks


def _supplement_tasks(question: str, tasks: tuple[QueryTask, ...], plan_context: dict[str, Any] | None = None) -> tuple[QueryTask, ...]:
    """Add real mv_* evidence queries for broad BI intents without hardcoded answers."""
    if plan_context:
        for requirement in plan_context.get("chart_requirements") or []:
            if not isinstance(requirement, dict):
                continue
            chart_text = " ".join(str(value).lower() for value in requirement.values())
            if any(keyword in chart_text for keyword in ("map", "geo", "folium", "mv_state_geo")):
                tasks = _prepend_task(tasks, _geo_task_key(plan_context=plan_context))
            if "heatmap" in chart_text and "payment" in chart_text:
                tasks = _append_task(tasks, "payment_heatmap")
        for view in plan_context.get("required_views") or []:
            tasks = _append_tasks_for_view(tasks, str(view), plan_context)
        if plan_context.get("analysis_type") == "predictive":
            tasks = _append_task(tasks, "monthly_sales")
            tasks = _append_task(tasks, "weekly_sales")
        if plan_context.get("analysis_type") == "prescriptive":
            for key in ("monthly_sales", "state_sales", "delivery_by_state", "category_sales", "payment_summary", "review_category"):
                tasks = _append_task(tasks, key)

    text = question.lower()
    if any(keyword in text for keyword in ("预测", "forecast", "未来6周", "未来 6 周")):
        tasks = _append_task(tasks, "monthly_sales")
        tasks = _append_task(tasks, "weekly_sales")
    if any(keyword in text for keyword in ("地图", "地理", "geo", "map", "巴西", "州级", "州分布")):
        tasks = _prepend_task(tasks, _geo_task_key(question, plan_context))
    if any(keyword in text for keyword in ("整体运营", "全部分析", "综合", "三大优先", "优先改进", "3个月", "三个月", "策略", "建议")):
        for key in ("monthly_sales", "state_sales", "delivery_by_state", "category_sales", "payment_summary", "review_category"):
            tasks = _append_task(tasks, key)
    if any(keyword in text for keyword in ("准时", "延迟", "配送", "交付", "delivery")):
        tasks = _append_task(tasks, "delivery_overall")
        tasks = _append_task(tasks, "delivery_by_state")
    if any(keyword in text for keyword in ("支付", "分期", "payment", "installment")):
        tasks = _append_task(tasks, "payment_summary")
        tasks = _append_task(tasks, "payment_heatmap")
    if any(keyword in text for keyword in ("差评", "评分", "评论", "review", "negative")):
        tasks = _append_task(tasks, "review_category")
    if any(keyword in text for keyword in ("卖家", "seller")):
        tasks = _append_task(tasks, "seller_review")
    if any(keyword in text for keyword in ("重量", "尺寸", "体积", "运费", "weight", "freight")):
        tasks = _append_task(tasks, "weight_freight")
    if "2017" in text and any(keyword in text for keyword in ("gmv", "销售额", "趋势", "各州", "州排名")):
        tasks = _append_task(tasks, "monthly_sales_2017")
        tasks = _append_task(tasks, "state_sales_2017")
    return tasks


def summarize_rows(rows: list[dict[str, Any]], columns: list[str]) -> str:
    """Create a compact Chinese data summary from query rows."""
    if not rows:
        return "查询成功，但结果为空。"
    parts = [f"返回 {len(rows)} 行，字段：{', '.join(columns)}。"]
    numeric_columns: list[str] = []
    for column in columns:
        if column == "sort_order":
            continue
        values = []
        for row in rows:
            try:
                if row[column] is not None and row[column] != "":
                    values.append(float(row[column]))
            except (TypeError, ValueError):
                pass
        if values and len(values) >= max(2, len(rows) // 3):
            numeric_columns.append(column)
            parts.append(f"{column} 均值 {mean(values):.2f}，最大 {max(values):.2f}，最小 {min(values):.2f}。")
        if len(numeric_columns) >= 3:
            break
    first = rows[0]
    parts.append("首行样例：" + ", ".join(f"{key}={first[key]}" for key in columns[:5]))
    return " ".join(parts)


def _execute_tasks(tasks: tuple[QueryTask, ...]) -> tuple[dict[str, QueryResult], dict[str, QueryRoute]]:
    """Execute SQL tasks and attach task context to any SQL failure."""
    results: dict[str, QueryResult] = {}
    routes: dict[str, QueryRoute] = {}
    for task in tasks:
        try:
            results[task.name] = run_query(task.sql)
            routes[task.name] = decide_query_route(task.sql)
        except Exception as exc:
            raise ValueError(f"SQL任务 {task.name} 执行失败：{exc}；SQL={task.sql}") from exc
    return results, routes


def _select_primary_task(question: str, tasks: tuple[QueryTask, ...], results: dict[str, QueryResult]) -> QueryTask:
    """Select the evidence task that best matches the user's current question."""
    text = question.lower()
    preferred_names: list[str] = []
    if any(keyword in text for keyword in ("支付", "分期", "payment", "installment", "boleto", "credit")):
        preferred_names.extend(["payment_summary", "payment_heatmap"])
    if any(keyword in text for keyword in ("差评", "评分", "评价", "评论", "低分", "反馈", "review", "negative")):
        preferred_names.append("review_category")
    if any(keyword in text for keyword in ("卖家", "seller")):
        preferred_names.append("seller_review")
    if any(keyword in text for keyword in ("重量", "尺寸", "体积", "运费", "运力成本", "weight", "freight")):
        preferred_names.append("weight_freight")
    if any(keyword in text for keyword in ("预测", "未来6周", "未来六周", "区间", "forecast")):
        preferred_names.extend(["weekly_sales", "monthly_sales"])
    if any(keyword in text for keyword in ("配送", "交付", "延迟", "准时", "物流", "履约", "delivery", "late")):
        preferred_names.extend(["delivery_by_state", "delivery_overall", "delivery_geo_map", "on_time_geo_map"])
    if any(keyword in text for keyword in ("品类", "产品组", "category", "health_beauty")):
        preferred_names.append("category_sales")
    if any(keyword in text for keyword in ("地图", "地理", "geo", "map", "巴西", "州级", "州分布")):
        preferred_names.extend(["state_geo_map", "delivery_geo_map", "on_time_geo_map", "seller_geo_map"])
    for preferred_name in preferred_names:
        for task in tasks:
            if task.name == preferred_name or task.name.startswith(f"{preferred_name}_"):
                if task.name in results:
                    return task
    return next((task for task in tasks if task.name in results), tasks[0])


def analyze_question(question: str, plan_context: dict[str, Any] | None = None) -> DataAnalysis:
    """Draft, route, execute, and summarize a business question."""
    tasks = _supplement_tasks(question, draft_tasks(question, plan_context=plan_context), plan_context)
    last_error: ValueError | None = None
    for repair_attempt in range(3):
        try:
            results, routes = _execute_tasks(tasks)
            break
        except ValueError as exc:
            last_error = exc
            if repair_attempt >= 2:
                raise ValueError(f"SQL 修复后仍执行失败：{exc}") from exc
            tasks = _supplement_tasks(question, repair_tasks_with_llm(question, tasks, str(exc), plan_context=plan_context), plan_context)
    else:
        raise ValueError(f"SQL 执行失败：{last_error}")
    # 地图类问题必须有经纬度结果；如果模型只查了州销售表，补查真实 mv_state_geo，
    # 只作为可视化证据补充，不替代大模型生成的业务 SQL。
    needs_geo = any(keyword in question.lower() for keyword in ("地图", "地理", "geo", "map", "巴西", "州级", "州分布", "热力"))
    plan_values = _plan_strings(plan_context)
    needs_geo = needs_geo or any(view == "mv_state_geo" for view in (plan_context or {}).get("required_views", [])) or any(
        "map" in str(item).lower() or "geo" in str(item).lower() for item in plan_values
    )
    has_geo_result = any({"customer_state", "lat", "lng"}.issubset(result.columns) for result in results.values())
    has_state_result = any("customer_state" in result.columns for result in results.values())
    if needs_geo and has_state_result and not has_geo_result:
        geo_task = SUPPLEMENTAL_TASKS[_geo_task_key(question, plan_context)]
        results[geo_task.name] = run_query(geo_task.sql)
        routes[geo_task.name] = decide_query_route(geo_task.sql)
        tasks = (*tasks, geo_task)
    primary = _select_primary_task(question, tasks, results)
    result = results[primary.name]
    route = routes[primary.name]
    summary_tasks = (primary, *(task for task in tasks if task.name != primary.name))
    summaries = [
        f"{task.purpose}：{summarize_rows(results[task.name].rows, results[task.name].columns)}"
        for task in summary_tasks
    ]
    direct_answer = build_direct_answer_from_results(question, results)
    return DataAnalysis(
        question=question,
        sql=primary.sql,
        tasks=tasks,
        route=route,
        routes=routes,
        result=result,
        results=results,
        summary="\n".join(summaries),
        direct_answer=direct_answer,
    )
